### ISSUE TITLE
[Home Page] - Create Submission Button

### ISSUE THREAD

**Issue by Fireworks** [boulderReactCodingNight/04-trails-app#1]
User should be able to click "Create Submission" button to navigate to the submission form.

Mockup: https://docs.google.com/drawings/d/1WIgBM3Nk-TmnEEfSPlwT2iLMjHFbr_tuZHi_pez7u5M/edit

**Comment by chuckb1789** [comment]
![image](https://user-images.githubusercontent.com/23364596/61501749-f22c8e80-a98d-11e9-87a5-2bb1ad0bb256.png)
