### ISSUE TITLE
[Home Page] - View Submission Button

### ISSUE THREAD

**Issue by Fireworks** [boulderReactCodingNight/04-trails-app#2]
User should be able to click "View Submissions" button to navigate to the submissions page.

Mockup: https://docs.google.com/drawings/d/1WIgBM3Nk-TmnEEfSPlwT2iLMjHFbr_tuZHi_pez7u5M/edit

**Comment by chuckb1789** [comment]
![image](https://user-images.githubusercontent.com/23364596/61501764-fd7fba00-a98d-11e9-993d-b71e3dad8ce6.png)
