### ISSUE TITLE
[ Condition List Page ] - Create Condition List Page

### ISSUE THREAD

**Issue by chuckb1789** [boulderReactCodingNight/04-trails-app#3]
Condition List Page
* User can see list of submitted conditions including:
    * Date submitted
    * Type
    * Location

![image](https://user-images.githubusercontent.com/23364596/59888643-ebf2c480-9385-11e9-841a-255cf6bc251a.png)

**Comment by emlabelle** [comment]
I'll take this

**Comment by jenniferwiner** [comment]
Merged code in via https://github.com/boulderReactCodingNight/04-trails-app/pull/13
