### ISSUE TITLE
[Condition Details Page] - View Condition Info

### ISSUE THREAD

**Issue by Fireworks** [boulderReactCodingNight/04-trails-app#8]
Users should be able to see information for a specific submission.

Mockup: https://docs.google.com/drawings/d/1WIgBM3Nk-TmnEEfSPlwT2iLMjHFbr_tuZHi_pez7u5M/edit

**Comment by relasine** [comment]
I'll grab this.

**Comment by relasine** [comment]
Styling and layout done.

**Comment by jenniferwiner** [comment]
Killin' it
